import { Response } from 'express';
import { AuthRequest } from '../middleware/auth';
import prisma from '../prisma';

export const getPaymentSettings = async (req: AuthRequest, res: Response) => {
  try {
    const keys = [
      'company_name',
      'company_address',
      'company_email',
      'company_phone',
      'company_tax_id',
      'default_currency',
      'default_tax_rate',
      'invoice_notes',
      'receipt_notes',
      'statement_footer_text',
      'paypal_client_id',
      'paypal_client_secret',
      'paypal_mode',
    ];

    const settings = await prisma.siteSetting.findMany({
      where: { key: { in: keys } },
    });

    const settingsMap: Record<string, string> = {
      company_name: 'AURA DIAMOND ATELIER',
      company_address: '740 Fifth Avenue, Suite 1800, New York, NY 10019',
      company_email: 'concierge@auroradiamonds.com',
      company_phone: '+1 (800) 555-2872',
      company_tax_id: 'US-TAX-88492019',
      default_currency: 'USD',
      default_tax_rate: '0',
      invoice_notes: 'Thank you for your business. Payment due within 14 days of invoice date.',
      receipt_notes: 'Official payment receipt generated by Aura Diamond Atelier.',
      statement_footer_text: 'For inquiries regarding this statement, please contact concierge@auroradiamonds.com.',
      paypal_client_id: '',
      paypal_client_secret: '',
      paypal_mode: 'sandbox',
    };

    settings.forEach((s) => {
      settingsMap[s.key] = s.value;
    });

    return res.status(200).json(settingsMap);
  } catch (error) {
    console.error('getPaymentSettings error:', error);
    return res.status(500).json({ message: 'Error retrieving payment settings' });
  }
};

export const updatePaymentSettings = async (req: AuthRequest, res: Response) => {
  try {
    const payload = req.body; // Key-value object

    const updatePromises = Object.entries(payload).map(async ([key, value]) => {
      const valStr = String(value);
      return prisma.siteSetting.upsert({
        where: { key },
        update: { value: valStr },
        create: { key, value: valStr },
      });
    });

    await Promise.all(updatePromises);

    // Audit log
    await prisma.financialAuditLog.create({
      data: {
        adminUser: req.user?.email || 'Admin',
        action: 'UPDATED_PAYMENT_SETTINGS',
        entityType: 'PAYMENT_SETTING',
        entityId: 'SYSTEM',
        newValue: 'Updated payment & statement configuration settings',
        reason: 'Settings updated via Admin panel',
      },
    });

    return res.status(200).json({ message: 'Payment settings saved successfully' });
  } catch (error) {
    console.error('updatePaymentSettings error:', error);
    return res.status(500).json({ message: 'Error updating payment settings' });
  }
};
